# Generated by Django 4.2.5 on 2025-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_appledjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='about_company',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
