# Generated by Django 4.2.5 on 2025-09-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_Label',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_Value',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='projectLabel',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='projectValue',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='aboutstitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='aboutussubtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='imageDescription',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='percentValue',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectCategoryName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectCategoryValue',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectTitle',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='seo_author',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='seo_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='seo_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
