# Generated by Django 4.2.5 on 2025-10-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_alter_category_category_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projectCategoryID',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectCategoryName',
            field=models.CharField(max_length=300),
        ),
    ]
