# Generated by Django 4.2.5 on 2025-07-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0002_services_pagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='menu_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
