# Generated by Django 4.2.5 on 2025-07-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0003_services_menu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='menu_Id',
            new_name='menu_ID',
        ),
    ]
