# Generated by Django 4.2.5 on 2025-07-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0004_rename_menu_id_services_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='page_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
