# Generated by Django 4.2.5 on 2025-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0005_services_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeature',
            name='services_page_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceaccordion',
            name='accordion_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='feature_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
