# Generated by Django 4.2.5 on 2025-07-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0006_servicefeature_services_page_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_postion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
